// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_rxEe9ZMriRNympRVYluRTVXsGAY5C8',
    appId: '1:231375212004:web:31860945ba567b21250bf1',
    messagingSenderId: '231375212004',
    projectId: 'test-520f7',
    authDomain: 'test-520f7.firebaseapp.com',
    storageBucket: 'test-520f7.appspot.com',
    measurementId: 'G-5W90F4B7BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8fPNz0cG1dW7Uqt6gjzB-NjkuQAg6Vvg',
    appId: '1:231375212004:android:5c8b1854015b14af250bf1',
    messagingSenderId: '231375212004',
    projectId: 'test-520f7',
    storageBucket: 'test-520f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4hyEDCVONdPm8-5H0fHOebaJu1yV-lvs',
    appId: '1:231375212004:ios:02c4da1423bef160250bf1',
    messagingSenderId: '231375212004',
    projectId: 'test-520f7',
    storageBucket: 'test-520f7.appspot.com',
    iosBundleId: 'com.example.previousLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4hyEDCVONdPm8-5H0fHOebaJu1yV-lvs',
    appId: '1:231375212004:ios:2f2da5ceba506213250bf1',
    messagingSenderId: '231375212004',
    projectId: 'test-520f7',
    storageBucket: 'test-520f7.appspot.com',
    iosBundleId: 'com.example.previousLife.RunnerTests',
  );
}
